### ISSUE TITLE
Does it support Playwright?

### ISSUE THREAD

**Issue by galaczi** [0qwertyy/puppeteer-extra-plugin-capsolver#1]
I would like to try it with my project but it's using Playwright. According to puppeteer-extra docs:

> New plugins will be based off automation-extra-plugin, which supports both Playwright & Puppeteer events

So I am wondering if this plugin is compatible with Playwright?

**Comment by 0qwertyy** [comment]
Hi galaczi, sorry but playwright is not covered yet by this plugin. It will works for puppeteer-extra based projects only. 
I'll add this for to-do stuffs but can't promise an update in a short time lapse. 
In the other hand, you can try to manage with my capsolver-npm (api wrapper/axios) for make your own code-adaptation.
Regards.

**Comment by andrisi** [comment]
Does it? With "playwright-extra"?
